### ISSUE TITLE
[10.0] Overriding field analytic_account_id in account.analytic.contract.line breaks link between account.analytic.invoice.line and account.analytic.account.

### ISSUE THREAD

**Issue by NL66278** [OCA/contract#124]
I have a module where I need to have partner_id as a reference field in account.analytic.invoice.line. This should not pose any problem, as account.analytic.invoice.line refers with account_analytic_id to account.analytic.account, which has partner id.

This is my code:
```python
  1 # -*- coding: utf-8 -*-                                                        
  2 # Copyright 2014-2017 Therp BV <https://therp.nl>.                             
  3 # License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).                
  4 from odoo import api, fields, models                                           
  5                                                                                
  6                                                                                
  7 class AccountAnalyticInvoiceLine(models.Model):                                
  8     _inherit = 'account.analytic.invoice.line'                                 
  9                                                                                
...                                                         
 23     partner_id = fields.Many2one(                                              
 24         comodel_name='res.partner',                                            
 25         related='analytic_account_id.partner_id',                              
 26         string='Partner') 
```

Unfortunately the code in contract/models/account_analytic_contract_line.py breaks the original analytic_account_id:
```python
  1 # -*- coding: utf-8 -*-                                                        
  2 # Copyright 2017 LasLabs Inc.                                                  
  3 # License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).                
  4                                                                                
  5 from odoo import fields, models                                                
  6                                                                                
  7                                                                                
  8 class AccountAnalyticContractLine(models.Model):                               
  9                                                                                
 10     _name = 'account.analytic.contract.line'                                   
 11     _description = 'Contract Lines'                                            
 12     _inherit = 'account.analytic.invoice.line'                                 
 13                                                                                
 14     analytic_account_id = fields.Many2one(                                     
 15         string='Contract',                                                     
 16         comodel_name='account.analytic.contract',                              
 17         required=True,                                                         
 18         ondelete='cascade',                                                    
 19     )
```
The result is this:
```
2017-11-23 10:41:23,674 13472 DEBUG odownbdem10 odoo.modules.loading: loading module publication (55/57)
2017-11-23 10:41:23,721 13472 ERROR odownbdem10 odoo.fields: Problem setting up related field partner_id for model account.analytic.contract.line
2017-11-23 10:41:23,721 13472 ERROR odownbdem10 odoo.modules.registry: Error setting up fields for model account.analytic.contract.line
2017-11-23 10:41:23,721 13472 ERROR odownbdem10 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/modules/loading.py", line 344, in load_modules
    loaded_modules, update_module)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/modules/loading.py", line 243, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/modules/loading.py", line 141, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/modules/registry.py", line 306, in setup_models
    model._setup_fields(partial)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/models.py", line 2850, in _setup_fields
    field.setup_full(self)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/fields.py", line 502, in setup_full
    self._setup_related_full(model)
  File "/home/openeyedev/var/projects/oe_woonbond_10/odoo/parts/odoo/odoo/fields.py", line 540, in _setup_related_full
    field = target._fields[name]
KeyError: 'partner_id'
```

**Comment by NL66278** [comment]
If we really want to have contracts (account.analytic.account) and contract templates (account.analytic.contract) in different models, I think it is a bad idea to have the inheritance defined from contracts to templates, but for lines in the other direction: from template lines to contract lines.

But maybe it would be better to have contracts and contract templates in the same models, with some fields als partner_id not required when used as a template.

Anyway that might be to big a change for now, but maybe there are good ideas to solve the problem without changing to much?

**Comment by pedrobaeza** [comment]
What about depending on the module contract?

**Comment by NL66278** [comment]
Issue can be solved, or should I say worked around, with this PR: https://github.com/OCA/contract/pull/129

**Comment by NL66278** [comment]
@pedrobaeza What did you mean with depending on contract? My code was depending on contract, that is how I ran into the issue described.

**Comment by katyukha** [comment]
May be related: #169

**Comment by NL66278** [comment]
Solved here: https://github.com/OCA/contract/commit/3c0c73c0f5aa63ae49a466c724722f938ca5eb87
