### ISSUE TITLE
Problem installing the module in Odoo 11

### ISSUE THREAD

**Issue by xabispacebiker** [OCA/contract#136]
Hi, I am new to Oddo and I get the following error when trying to install the module:

```
Traceback (most recent call last):
  File "/home/odoo/odoo11/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo11/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/odoo11/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/odoo/odoo11/odoo/odoo/addons/base/ir/ir_cron.py", line 69, in create
    return super(ir_cron, self).create(values)
  File "/home/odoo/odoo11/odoo/odoo/models.py", line 3277, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo11/odoo/odoo/models.py", line 3334, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/home/odoo/odoo11/odoo/odoo/addons/base/ir/ir_actions.py", line 46, in create
    res = super(IrActions, self).create(vals)
  File "/home/odoo/odoo11/odoo/odoo/models.py", line 3277, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo11/odoo/odoo/models.py", line 3370, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/odoo11/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo11/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (356, Generate Recurring Invoices from Contracts, ir.actions.server, null, null, action, 1, 2018-01-03 14:27:43.959774, 1, 2018-01-03 14:27:43.959774, ir_cron, object_write, 5, null, null, # Available variables:
#  - env: Odoo Environment on which the a..., null, null, null).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo11/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo11/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo11/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo11/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo11/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo11/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo11/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo11/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo11/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo11/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo11/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo11/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo11/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/home/odoo/odoo11/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/odoo11/odoo/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/odoo11/odoo/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/odoo11/odoo/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo11/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/odoo11/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/odoo11/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/odoo11/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo11/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo11/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo11/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/odoo/odoo11/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo11/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo11/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/odoo11/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/odoo/odoo11/odoo/odoo/addons/base/ir/ir_cron.py", line 69, in create
    return super(ir_cron, self).create(values)
  File "/home/odoo/odoo11/odoo/odoo/models.py", line 3277, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo11/odoo/odoo/models.py", line 3334, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/home/odoo/odoo11/odoo/odoo/addons/base/ir/ir_actions.py", line 46, in create
    res = super(IrActions, self).create(vals)
  File "/home/odoo/odoo11/odoo/odoo/models.py", line 3277, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo11/odoo/odoo/models.py", line 3370, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/odoo11/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo11/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (356, Generate Recurring Invoices from Contracts, ir.actions.server, null, null, action, 1, 2018-01-03 14:27:43.959774, 1, 2018-01-03 14:27:43.959774, ir_cron, object_write, 5, null, null, # Available variables:
#  - env: Odoo Environment on which the a..., null, null, null).
" while parsing /home/odoo/odoo11/odoo/addons/contract/data/contract_cron.xml:4, near
<record model="ir.cron" id="account_analytic_cron_for_invoice">
        <field name="name">Generate Recurring Invoices from Contracts</field>
        <field name="interval_number">1</field>
        <field name="interval_type">days</field>
        <field name="numbercall">-1</field>
        <field name="model" eval="'account.analytic.account'"/>
        <field name="function" eval="'cron_recurring_create_invoice'"/>
        <field name="args" eval="'()'"/>
    </record>
  
```

**Comment by pedrobaeza** [comment]
You don't have latest version.
