### ISSUE TITLE
[11.0] error message by settings

### ISSUE THREAD

**Issue by ghost** [OCA/contract#179]
On menupoint "settings" i get this error-message:

```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/share/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fbd1ee16d68>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/share/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fbd1ee16c50>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/share/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fbd1ee16c50>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/share/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/share/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/share/odoo/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/share/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/share/odoo/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/share/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/share/odoo/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/share/odoo/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/share/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/share/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/models.py", line 5127, in onchange
    for name in dirty
  File "/usr/share/odoo/odoo/odoo/models.py", line 5127, in <dictcomp>
    for name in dirty
  File "/usr/share/odoo/odoo/odoo/fields.py", line 2019, in convert_to_onchange
    return super(Many2one, self).convert_to_onchange(value, record, names)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 810, in convert_to_onchange
    return self.convert_to_read(value, record)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 2000, in convert_to_read
    return (value.id, value.sudo().display_name)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/usr/share/odoo/odoo/odoo/models.py", line 1489, in _compute_display_name
    names = dict(self.name_get())
  File "/usr/share/odoo/odoo/odoo/models.py", line 1508, in name_get
    result.append((record.id, convert(record[name], record)))
  File "/usr/share/odoo/odoo/odoo/models.py", line 4758, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/share/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1001, in _compute_value
    self.compute(records)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 589, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "/usr/share/odoo/odoo/odoo/models.py", line 4758, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/share/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1042, in determine_value
    record._prefetch_field(self)
  File "/usr/share/odoo/odoo/odoo/models.py", line 2646, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/share/odoo/odoo/odoo/models.py", line 2590, in read
    self._read_from_database(stored, inherited)
  File "/usr/share/odoo/odoo/odoo/models.py", line 2709, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/share/odoo/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column account_analytic_account.contract_type does not exist
LINE 1: ..._analytic_account"."create_date" as "create_date","account_a...
```
                                                             ^

**Comment by pedrobaeza** [comment]
You have to update your module, as always.

**Comment by ghost** [comment]
sure, i have done it. on webinterface and command-line, too.

**Comment by pedrobaeza** [comment]
Then you should restart your Odoo service. It's the usual stuff.

**Comment by ghost** [comment]
All you offer i have done.
```
docker exec buwe-odoo /usr/share/odoo/bin/python3 /usr/share/odoo/odoo/odoo-bin -c /etc/odoo/odoo.conf --no-http -u contract,account --stop-after-init
docker restart buwe-odoo
```
This is what i have done.
Odoo says: "Well done! All your Apps are up-to-date! "

**Comment by pedrobaeza** [comment]
No, that's a total nonsense! This is only Online apps Odoo market saying you there's not any updated app to download, but this is totally out of online flows. You should install `disable_odoo_online` module for not getting confused with that thing, and get used of the integrator flows, updating for example via command line.

**Comment by ghost** [comment]
Ok, i understood.

After rebuild my docker-image with new github-download i make a upgrade for all modules and restart docker instance ... i get the error. with the old container it runs.
Pedro, thx for your advice.
