### ISSUE TITLE
Web responsive OCA module incompatibility 

### ISSUE THREAD

**Issue by ghost** [OCA/contract#275]
Hi, installing Web responsive OCA module (https://www.odoo.com/apps/modules/11.0/web_responsive/)
and error trigger when clicking on contracts.

We use Odoo 11 and started with this version, is not a migration. I took a look on web_responsive issues but no one is posted and I'm not sure if that's a contract issue or a web_responsive issue.

Thanks in advance.
Error:
Uncaught Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found
http://xxxx/web/content/322-3e58a25/web.assets_common.js:3689
Rastreo de error:
Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found
    at Object.exception (http://xxxx/web/content/322-3e58a25/web.assets_common.js:3689:7)
    at Engine._render (http://xxxx/web/content/322-3e58a25/web.assets_common.js:3734:103)
    at Engine.render (http://xxxx/web/content/322-3e58a25/web.assets_common.js:3730:151)
    at Class._renderHeaderButtons (http://xxxx/web/content/1090-30c82bb/web.assets_backend.js:2970:502)
    at Class._renderHeaderButtons (http://xxxx/web/content/322-3e58a25/web.assets_common.js:3819:371)
    at Class._renderTagHeader (http://xxxx/web/content/1090-30c82bb/web.assets_backend.js:1400:359)
    at Class._renderNode (http://xxxx/web/content/1090-30c82bb/web.assets_backend.js:1390:246)
    at Class._renderNode (http://xxxx/web/content/1090-30c82bb/web.assets_backend.js:2339:51)
    at Class._renderNode (http://xxxx/web/content/322-3e58a25/web.assets_common.js:3819:371)
    at Function._.map._.collect (http://xxxx/web/content/322-3e58a25/web.assets_common.js:13:270)

**Comment by pedrobaeza** [comment]
I don't think it's something of web_responsive, as we have it working since a lot with both modules together. Please put the steps to have the error.

**Comment by pedrobaeza** [comment]
Closing as no answer.
