### ISSUE TITLE
Templates section/ new agreement dont copy section clauses

### ISSUE THREAD

**Issue by Ilyasse-ouza8** [OCA/contract#323]
when i try to make a new agreement from a template , the created agreement dont have it section clauses , and the clauses will be just duplicated and related to the template.

**Comment by pedrobaeza** [comment]
Version? Module? Screenshots?

**Comment by Ilyasse-ouza8** [comment]
v12,  i think it got fixed , i just added  copy =true in  clauses_ids field  that belongs to  agreement.section  model .

the problem was that the copy in the method 

> create_new_agreement

  couldn't duplicates the clauses of a section


![image](https://user-images.githubusercontent.com/45516560/57320154-c3707d00-70ed-11e9-951d-bf7b8acee43c.png)

**Comment by Ilyasse-ouza8** [comment]
this morning i got this exception from the modification `copy=True`  saying that object is not subscriptable , anyone knows the problem ?

```
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/addons/ilyasse-stock/contract/agreement_legal/models/agreement.py", line 446, in create_new_agreement
    res = self.copy(default_vals)
  File "/odoo/odoo-server/odoo/models.py", line 4247, in copy
    vals = self.copy_data(default)[0]
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 349, in copy_data
    return super(MailThread, self.with_context(mail_notrack=True)).copy_data(default=default)
  File "/odoo/odoo-server/odoo/models.py", line 4151, in copy_data
    lines = [rec.copy_data()[0] for rec in self[name].sorted(key='id')]
  File "/odoo/odoo-server/odoo/models.py", line 4151, in <listcomp>
    lines = [rec.copy_data()[0] for rec in self[name].sorted(key='id')]
  File "/odoo/odoo-server/odoo/models.py", line 4151, in copy_data
    lines = [rec.copy_data()[0] for rec in self[name].sorted(key='id')]
  File "/odoo/odoo-server/odoo/models.py", line 4151, in <listcomp>
    lines = [rec.copy_data()[0] for rec in self[name].sorted(key='id')]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Ilyasse-ouza8** [comment]
the problem only happens when i assigne an agreement to the clauses of a section , in the `agreement` field below.  
![image](https://user-images.githubusercontent.com/45516560/57370250-36760400-717f-11e9-93a2-22f362e8be64.png)

**Comment by max3903** [comment]
@Ilyasse-ouza8 Can you test the fix at #324 and confirm the bug is solved?

**Comment by Ilyasse-ouza8** [comment]
the copy works perfectly , all it needs now is just to assign the clauses to the new agreement and detache them from the template(because in the new agreement clauses are assigned to the template )

**Comment by max3903** [comment]
@Ilyasse-ouza8 Fixed.

**Comment by Ilyasse-ouza8** [comment]
@max3903  perfect.
