### ISSUE TITLE
[12.0][BUG] agreement_legal: new agreement button (template form)

### ISSUE THREAD

**Issue by ygol** [OCA/contract#342]
1. Create a template
2. add at least 2 sections
3. click on button "new agreement" generate the following error:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/models.py", line 4698, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/contract/agreement_legal/models/agreement.py", line 353, in create_new_agreement
    res.sections_ids.clauses_ids.write({'agreement_id': res.id})
  File "/.repo_requirements/odoo/odoo/fields.py", line 979, in __get__
    record.ensure_one()
  File "/.repo_requirements/odoo/odoo/models.py", line 4701, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: agreement.section(3, 4)
```

**Comment by pedrobaeza** [comment]
Closing as there's an opened PR for this.

**Comment by pedrobaeza** [comment]
@ygol if you intend to the PR for fixing the bug, please don't open both issue and PR, just the PR, and put the issue text there.
