### ISSUE TITLE
Error ading product to Contract

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/contract#351]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5204, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5021, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/custom.addons/contract/contract/models/account_analytic_contract_line.py", line 220, in _onchange_product_id
    vals['price_unit'] = product.price
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4590, in update
    record[name] = value
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4794, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 966, in __set__
    value = self.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1990, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for account.analytic.invoice.line.uom_id: product.uom(1,)

**Comment by pedrobaeza** [comment]
Version? Steps to reproduce?

**Comment by marcos-mendez** [comment]
> Version? Steps to reproduce?

Just adding a new product to the contract 

Odoo V11.0

**Comment by pedrobaeza** [comment]
Uhm, I don't think so... I'm using it since a long. It seems an interaction with other third-party module you have. Check that is working properly in https://runbot.odoo-community.org/runbot/110/11.0

**Comment by marcos-mendez** [comment]
Whell How can it be if i just git cloned the OCA/contract repository?

**Comment by pedrobaeza** [comment]
Please try to reproduce it in the runbot link that I have put you.
