### ISSUE TITLE
Agreement report from sale order

### ISSUE THREAD

**Issue by carlo-github** [OCA/contract#359]
1- installed the modules agreement_legal_sale
2- created a sale order with 2 product and the agreement template "[BUY-VOIP013] SIP-ISDN gateways"
3- in the agreement I added a line in Section where I put in Content
${object.agreement_id.sale_id.order_line.name or ''}
4- print with Contract Document obtain the error:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 14

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('agreement.section(14,).dynamic_content', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 335, in _render_template
    render_result = template.render(variables)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 385, in getattr
    value = getattr(obj, attribute)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 979, in __get__
    record.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4721, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: sale.order.line(64, 65)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_871_227
  File "<template>", line 3, in body_call_content_226
  File "<template>", line 4, in foreach_225
  File "<template>", line 5, in body_call_content_224
  File "<template>", line 56, in foreach_212
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 387, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb_fields.py", line 125, in record_to_html
    value = record[field_name]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5117, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1043, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/agreement_legal/models/agreement_section.py", line 62, in _compute_dynamic_content
    section.content, "agreement.section", section.id)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 338, in _render_template
    raise UserError(_("Failed to render template %r using values %r")% (template, variables))
odoo.exceptions.UserError: ("Failed to render template <Template memory:7fb528068b38> using values {'format_date': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb513a5df28>, 'format_tz': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb5136bfe18>, 'format_amount': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb5136bfa60>, 'user': res.users(2,), 'ctx': {'lang': 'en_US', 'tz': 'Europe/Brussels', 'uid': 2, 'commit_assetsbundle': True, 'debug': False}, 'object': agreement.section(14,)}", '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1671, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 711, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 751, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 534, in render_template
    return view_obj.render_template(template, values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1284, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1293, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 274, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: ("Failed to render template <Template memory:7fb528068b38> using values {'format_date': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb513a5df28>, 'format_tz': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb5136bfe18>, 'format_amount': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb5136bfa60>, 'user': res.users(2,), 'ctx': {'lang': 'en_US', 'tz': 'Europe/Brussels', 'uid': 2, 'commit_assetsbundle': True, 'debug': False}, 'object': agreement.section(14,)}", '')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 14

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('agreement.section(14,).dynamic_content', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 335, in _render_template
    render_result = template.render(variables)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 385, in getattr
    value = getattr(obj, attribute)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 979, in __get__
    record.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4721, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: sale.order.line(64, 65)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_871_227
  File "<template>", line 3, in body_call_content_226
  File "<template>", line 4, in foreach_225
  File "<template>", line 5, in body_call_content_224
  File "<template>", line 56, in foreach_212
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 387, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb_fields.py", line 125, in record_to_html
    value = record[field_name]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5117, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1043, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/agreement_legal/models/agreement_section.py", line 62, in _compute_dynamic_content
    section.content, "agreement.section", section.id)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 338, in _render_template
    raise UserError(_("Failed to render template %r using values %r")% (template, variables))
odoo.exceptions.UserError: ("Failed to render template <Template memory:7fb528068b38> using values {'format_date': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb513a5df28>, 'format_tz': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb5136bfe18>, 'format_amount': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb5136bfa60>, 'user': res.users(2,), 'ctx': {'lang': 'en_US', 'tz': 'Europe/Brussels', 'uid': 2, 'commit_assetsbundle': True, 'debug': False}, 'object': agreement.section(14,)}", '')

Error to render compiling AST
UserError: ("Failed to render template <Template memory:7fb528068b38> using values {'format_date': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb513a5df28>, 'format_tz': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb5136bfe18>, 'format_amount': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fb5136bfa60>, 'user': res.users(2,), 'ctx': {'lang': 'en_US', 'tz': 'Europe/Brussels', 'uid': 2, 'commit_assetsbundle': True, 'debug': False}, 'object': agreement.section(14,)}", '')
Template: 871
Path: /templates/t/t/t/t/t/div[1]/table[2]/tbody/tr/td/ol/li/p
Node: <p t-field="s.dynamic_content"/>
```

os: ubuntu 18.04
Odoo 12.0-20190705
odoo db new clean with demo data
agrement modules downloaded 02 aug 2019

**Comment by max3903** [comment]
@carlo-github 2 things here:

1. The correct process is to validate the sales order first. That will create the agreement with the content from the template and the customer information from the sales order. It will also copy the sales order lines to the agreement lines.
2. If you want to show agreement lines information in the content (of a section, clause, appendix or recital), you need to loop through the lines as you may have multiple agreement lines... If you need further help or example to achieve that, let me know.

**Comment by max3903** [comment]
@osi-scampbell Can you fix this to avoid the stacktrace? Let's show the first record if we get multiple ones.

**Comment by carlo-github** [comment]
> @carlo-github 2 things here:
> 
> 1. The correct process is to validate the sales order first. That will create the agreement with the content from the template and the customer information from the sales order. It will also copy the sales order lines to the agreement lines.
> 2. If you want to show agreement lines information in the content (of a section, clause, appendix or recital), you need to loop through the lines as you may have multiple agreement lines... If you need further help or example to achieve that, let me know.

Thank you for the answer.. but as I'm not so skilled in this issue.. if you are so kind to give me more information or example.. willl be very appreciate.. Yes, I tried with an order with a single line and I was able to print it in the agreement, but with more then 1 line I had some trouble. My goal is to print in the agreement obtained from the SO the lines in it..

**Comment by osi-scampbell** [comment]
@carlo-github For your problem, the best way to implement @max3903 solution is to open the Section and add the following code. Make sure you are in the 'Code View' of the content field. 
![image](https://user-images.githubusercontent.com/39602586/62488401-143d5380-b779-11e9-83a8-cb01c0b67060.png)

You should get the following output:
![image](https://user-images.githubusercontent.com/39602586/62488484-3f27a780-b779-11e9-8cc8-3cd57d35a3e6.png)

**Comment by carlo-github** [comment]
> @carlo-github For your problem, the best way to implement @max3903 solution is to open the Section and add the following code. Make sure you are in the 'Code View' of the content field.
> ![image](https://user-images.githubusercontent.com/39602586/62488401-143d5380-b779-11e9-83a8-cb01c0b67060.png)
> 
> You should get the following output:
> ![image](https://user-images.githubusercontent.com/39602586/62488484-3f27a780-b779-11e9-8cc8-3cd57d35a3e6.png)

@osi-scampbell 
Thank you very much for the suggest.. I was able to print what I searched.
With this code I print the values..
```
<ul>
% set lines = object.agreement_id.sale_id.order_line
% for line in lines:
    <li>${line.product_uom_qty} ${line.product_id.categ_id.parent_path} ${line.name}</li>
% endfor
</ul>

```

**Question 1**
I would like to print only some products from the SO depending on the product category.. for instance the product with category 1/2/5/.. I suppose need one if statement but I'm a beginner and I tried to search on the web for a solution.. every time the syntax was incorrect..
This is an example that doesn't work..
```
<ul>
% set lines = object.agreement_id.sale_id.order_line
% for line in lines:
    <t t-set=”categoria” t-value="${line.product_id.categ_id.parent_path}"/>
    <t t-if=”categoria==1/2/5/”> <li>${line.product_uom_qty} ${line.product_id.categ_id.parent_path} ${line.name}</li></t>
% endfor
</ul>
```

**Question 2**
Is then possible to print all the products (name and code) even if they aren't in the SO.. for instance all the products from the database or the products of a specific category.. without any link to the agreement..?

**Comment by pedrobaeza** [comment]
Is this still happening? Which version?

**Comment by carlo-github** [comment]
With Odoo 12.0-20200116 (Community Edition)
In any case, for obtain what I asked there was a development from my side.
Thank you.

**Comment by pedrobaeza** [comment]
@max3903 should we close this then?
