### ISSUE TITLE
Error on Agreement Object

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/contract#362]
The error is generated when any user assigned to Agreement User or Manager tryes to edit a contact or access the agreement module
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2591, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2752, in _read_from_database
    field.read(fetched)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2264, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1481, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3796, in _search
    self._apply_ir_rules(query, 'read')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3646, in _apply_ir_rules
    where_clause, where_params, tables = Rule.domain_get(self._name, mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_rule.py", line 116, in domain_get
    query = self.env[model_name].sudo()._where_calc(dom, active_test=False)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3585, in _where_calc
    e = expression.expression(domain, self)
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 668, in __init__
    self.parse()
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 846, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'company_id' in leaf "<osv.ExtendedLeaf: ('company_id', '=', False) on agreement (ctx: )>"
```

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by marcos-mendez** [comment]
Yes.

Em seg, 4 de mai de 2020 06:53, Pedro M. Baeza <notifications@github.com>
escreveu:

**Comment by pedrobaeza** [comment]
@max3903 any news about this?
