### ISSUE TITLE
[12.0][BUG] agreement_legal: broken mass actions due incorrect implentation of overrided write-method of model

### ISSUE THREAD

**Issue by oleg-babintsev** [OCA/contract#494]
1. Create several agreements
2. Select more than one records on the list view
3. Call mass-action "Archive" as example
```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 4732, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/others/oca_contract/odoo/addons/agreement_legal/models/agreement.py", line 372, in write
    vals["revision"] = self.revision + 1
  File "/opt/odoo/odoo/fields.py", line 1003, in __get__
    record.ensure_one()
  File "/opt/odoo/odoo/models.py", line 4735, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: agreement(4, 5)
```

**Comment by newtratip** [comment]
Fixed in https://github.com/OCA/contract/pull/637/
