### ISSUE TITLE
[12.0] Updating product_contract -> AttributeError: module 'openupgradelib.openupgrade' has no attribute 'convert_to_company_dependent'

### ISSUE THREAD

**Issue by miscs** [OCA/contract#514]
Hi all,

I am having problems upgrading product_contract (error see below).

openupgradelib is installed and up-to-date:
Requirement already satisfied: cssselect in /usr/local/lib/python3.6/dist-packages (from openupgradelib==3.0.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.6/dist-packages (from openupgradelib==3.0.0)

Any hints are highly appreciated!
Thanks
Steve

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 627, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/odoo-server/odoo/modules/migration.py", line 190, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1734, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/custom/addons/product_contract/migrations/12.0.4.0.0/pre-migration.py", line 30, in migrate
    openupgrade.convert_to_company_dependent(
AttributeError: module 'openupgradelib.openupgrade' has no attribute 'convert_to_company_dependent'

**Comment by sbejaoui** [comment]
Hi,

You need to use the very last version (master) of openupgradelib to be able to update product_contract module.

This PR  https://github.com/OCA/openupgradelib/pull/197 that add `convert_to_company_dependent` was merged in openupgradelib but there is no new tag yet.

Regards.

**Comment by pedrobaeza** [comment]
Use `pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master`

**Comment by miscs** [comment]
thank you, that worked!
