### ISSUE TITLE
Error update contract

### ISSUE THREAD

**Issue by bylli79** [OCA/contract#525]
Hello,
I have updated the git.
Odoo does not start generating the following error:

2020-06-10 22: 57: 02,869 11 CRITICAL bsgest odoo.service.server: Failed to initialize database `gest`.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/service/server.py", line 1042, in preload_registries
    registry = Registry.new (dbname, update_module = update_module)
  File "/opt/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules (registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks = perform_checks, models_to_check = models_to_check
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module (package, 'pre')
  File "/opt/odoo/odoo-server/odoo/modules/migration.py", line 178, in migrate_module
    migrate (self.cr, installed_version)
  File "/opt/odoo/datadir/addons/12.0/contract/migrations/12.0.5.0.0/pre-migration.py", line 9, in migrate
    "" "
  File "/opt/odoo/odoo-server/odoo/sql_db.py", line 148, in wrapper
    return f (self, * args, ** kwargs)
  File "/opt/odoo/odoo-server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute (query, params)
psycopg2.ProgrammingError: relation "contract_line" does not exist
LINE 1: UPDATE contract_line

What can I do?

Thanks

**Comment by pedrobaeza** [comment]
This is a problem in your end. You have to update the module in the DB.
