### ISSUE TITLE
[10.0] Scheduler 'Generate Recurring Invoices' doesn't work

### ISSUE THREAD

**Issue by mgielissen** [OCA/contract#53]
When running the scheduler, this errror shows up:

2017-02-21 09:49:54,080 2663 ERROR openworx odoo.addons.base.ir.ir_cron: Call of self.env[u'account.analytic.account'].cron_recurring_create_invoice(*()) failed in Job 9
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_cron.py", line 119, in _callback
    getattr(model, method_name)(*args)
  File "/opt/odoo/addons/contract/models/contract.py", line 291, in cron_recurring_create_invoice
    return contracts.recurring_create_invoice()
  File "/opt/odoo/addons/contract/models/contract.py", line 280, in recurring_create_invoice
    contract.with_context(ctx)._create_invoice()
  File "/opt/odoo/addons/contract/models/contract.py", line 260, in _create_invoice
    invoice_line_vals = self._prepare_invoice_line(line, invoice.id)
  File "/opt/odoo/addons/contract/models/contract.py", line 209, in _prepare_invoice_line
    self.env.context['next_date'], date_format)
  File "/opt/odoo/addons/contract/models/contract.py", line 183, in _insert_markers
    name = name.replace('#START#', date_from.strftime(date_format))
**ValueError: year=1017 is before 1900; the datetime strftime() methods require year >= 1900**

**Comment by pedrobaeza** [comment]
You have put an invalid date in your contract.
