### ISSUE TITLE
[12.0][BUG] Querying contracts from contacts 2nd chance.

### ISSUE THREAD

**Issue by Lopsanz** [OCA/contract#568]
Steps to reproduce:
1.- Go to contacts and group the listview by country 
2.- Navigate into contact form view
3.- Clic on contracts smartbutton. All is OK at the first time.
4.- Back to contact
5.- Clic on contracts smartbutton again.

Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 2092, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/.repo_requirements/odoo/odoo/models.py", line 2120, in _read_group_raw
    annotated_groupbys = [self._read_group_process_groupby(gb, query) for gb in groupby_list]
  File "/.repo_requirements/odoo/odoo/models.py", line 2120, in <listcomp>
    annotated_groupbys = [self._read_group_process_groupby(gb, query) for gb in groupby_list]
  File "/.repo_requirements/odoo/odoo/models.py", line 1923, in _read_group_process_groupby
    field_type = self._fields[split[0]].type
KeyError: country_id

NOTE: In my odoo instance, error is replicated also selecting a group if field is not in contract model
Same test doesn't crash in odoo 13

**Comment by pedrobaeza** [comment]
I think this problem comes from https://github.com/odoo/odoo/issues/47680

**Comment by Lopsanz** [comment]
https://github.com/OCA/contract/blob/924e73be0539ee55ae021b9c51bdc7ecf94083ec/contract/models/res_partner.py#L51

Since that related issue is not solved, perhaps we should remove "group by" received in self.env.context

**Comment by Lopsanz** [comment]
#569
