### ISSUE TITLE
Upgrade to 13.0.2.2.0 fails - contract/security/ir.model.access.csv could not be processed

### ISSUE THREAD

**Issue by aschlager** [OCA/contract#605]
Trying to update from 13.0.1.0.3 (with already existing contracts in the system) to 13.0.2.2.0, I get this error while updating:

`
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo_test/odoo_test-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo_test/odoo_test-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo_test/odoo_test-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo_test/odoo_test-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo_test/odoo_test-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo_test/odoo_test-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo_test/odoo_test-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo_test/odoo_test-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo_test/odoo_test-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo_test/odoo_test-server/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo_test/odoo_test-server/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo_test/odoo_test-server/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo_test/odoo_test-server/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-65>", line 2, in button_immediate_upgrade
  File "/opt/odoo_test/odoo_test-server/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo_test/odoo_test-server/odoo/addons/base/models/ir_module.py", line 634, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo_test/odoo_test-server/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo_test/odoo_test-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo_test/odoo_test-server/odoo/modules/loading.py", line 419, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo_test/odoo_test-server/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo_test/odoo_test-server/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo_test/odoo_test-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo_test/odoo_test-server/odoo/tools/convert.py", line 732, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/odoo_test/odoo_test-server/odoo/tools/convert.py", line 779, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading contract failed: file contract/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_contract_modification' in field 'Object'
No matching record found for external id 'model_contract_modification' in field 'Object'
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
`

**Comment by pedrobaeza** [comment]
It seems you haven't update properly, as the model is added in such version.

**Comment by aschlager** [comment]
I only hit the "upgrade" button in the Module Info page, nothing else.
Anything to prepare which I missed?

**Comment by pedrobaeza** [comment]
Are you talking about the Apps online option? That one doesn't normally works.

**Comment by aschlager** [comment]
Sorry if I haven't described before: I'm using Odoo 13 CE on a own Ubuntu server machine.
Now looked into odoo server log, I discovered this:
2021-01-05 19:38:44,326 20333 INFO bexodoo01 odoo.modules.loading: loading contract/security/groups.xml 
2021-01-05 19:38:44,486 20333 INFO bexodoo01 odoo.modules.loading: loading contract/security/contract_tag.xml 
2021-01-05 19:38:44,503 20333 INFO bexodoo01 odoo.modules.loading: loading contract/security/ir.model.access.csv 
2021-01-05 19:38:44,573 20333 ERROR bexodoo01 odoo.sql_db: bad query: INSERT INTO "ir_model_access" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "group_id", "name", "perm_create", "perm_read", "perm_unlink", "perm_write") VALUES (nextval('ir_model_access_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), true, 35, 'Contract modifications - User', true, true, true, true) RETURNING id
ERROR: null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (802, Contract modifications - User, t, null, 35, t, t, t, t, 1, 2021-01-05 19:38:41.931605, 1, 2021-01-05 19:38:41.931605).
 
2021-01-05 19:38:44,608 20333 ERROR bexodoo01 odoo.sql_db: bad query: INSERT INTO "ir_model_access" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "group_id", "name", "perm_create", "perm_read", "perm_unlink", "perm_write") VALUES (nextval('ir_model_access_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), true, 35, 'Contract modifications - User', true, true, true, true) RETURNING id
ERROR: null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (805, Contract modifications - User, t, null, 35, t, t, t, t, 1, 2021-01-05 19:38:41.931605, 1, 2021-01-05 19:38:41.931605).
 
2021-01-05 19:38:44,611 20333 ERROR bexodoo01 odoo.sql_db: bad query: INSERT INTO "ir_model_access" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "group_id", "name", "perm_create", "perm_read", "perm_unlink", "perm_write") VALUES (nextval('ir_model_access_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), true, 8, 'Contract modifications - Portal', false, true, false, false) RETURNING id
ERROR: null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (806, Contract modifications - Portal, t, null, 8, t, f, f, f, 1, 2021-01-05 19:38:41.931605, 1, 2021-01-05 19:38:41.931605).
 
2021-01-05 19:38:44,893 20333 WARNING bexodoo01 odoo.modules.loading: Transient module states were reset 
2021-01-05 19:38:44,895 20333 ERROR bexodoo01 odoo.modules.registry: Failed to load registry

**Comment by pedrobaeza** [comment]
Previously there should be the model update. Something is not correct on your side, sorry. It's nothing of the module itself.

**Comment by Boca13** [comment]
@aschlager maybe you can fix your problem by updating the module from the CLI. I mean, launch Odoo like this:
`odoo-bin -u contract -d YOUR_DATABASE`. More information: https://www.odoo.com/documentation/13.0/reference/cmdline.html
