### ISSUE TITLE
Force removal

### ISSUE THREAD

**Issue by frantischek** [OCA/contract#636]
Hello,
I need to remove the contract app from my odoo because it produces some errors (I'm using odoo 14 and contract for version 13.) 
Can someone tell me how to remove it using SSH, because when I try to uninstall it I get this error: 

```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1377, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6198, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6000, in __init__
    self.fetch(name)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6008, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6008, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6000, in __init__
    self.fetch(name)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6010, in fetch
    self[name] = record[name]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5641, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 999, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1138, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4036, in _compute_field_value
    getattr(self, field.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 202, in _compute_count
    records = self.env[model.model]
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'contract.contract'
```
`

**Comment by flotho** [comment]
hummm...
As you can imagine, mixing version is really not the best way to get a stable environment.
Yet, you clearly experienced something that could be the same in openupgrade process.
The db cleanup module is the appropriate one to be able to handle this, sadly it's not available in v14 for nom.
Then you'll have to do it the hard way but not by SSH.

1 - check the state of your module via Odoo and check what is the version displayed and stored in the manifest (via ssh)
2 - Check in the model list if contract.contract is available (obviously not)
3 - go to the external id list and filter everything that is a field or a model starting with contract.contract

regarding this situation you'll be able to delete some external id to ease the desinstallation process.
