### ISSUE TITLE
Contract V13 - TypeError: _values_to_save() got an unexpected keyword argument 'all_fields'

### ISSUE THREAD

**Issue by julienb31** [OCA/contract#651]
Hi,
I have an issue following the installation of the contract module.
This error is generated when the action "create invoices" of a contract is activated.
Can you please help me find the reason for this blockage?

Here are the details of the error:

Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/contract/models/contract.py", line 528, in recurring_create_invoice
    invoice = self._recurring_create_invoice()
  File "/opt/odoo/odoo/addons/contract/models/contract.py", line 555, in _recurring_create_invoice
    invoices_values = self._prepare_recurring_invoices_values(date_ref)
  File "/opt/odoo/odoo/addons/contract/models/contract.py", line 511, in _prepare_recurring_invoices_values
    invoice_vals, move_form = contract._prepare_invoice(date_ref)
  File "/opt/odoo/odoo/addons/contract/models/contract.py", line 403, in _prepare_invoice
    invoice_vals = move_form._values_to_save(all_fields=True)
TypeError: _values_to_save() got an unexpected keyword argument 'all_fields'

**Comment by pedrobaeza** [comment]
You have some kind of bad overriding of such method, as the argument is correct:

https://github.com/odoo/odoo/blob/1e35b8987c619f200e84da2ba97040b38347edde/odoo/tests/common.py#L1731
