### ISSUE TITLE
[10.0][BUG][contract] Error when adding a product in a invoice line when creating a contract template

### ISSUE THREAD

**Issue by rafaelbn** [OCA/contract#68]
- Go to runbot: in my case: http://3290495-10-0-ea6f03.runbot2.odoo-community.org/web?debug
- Create a contract and save
- Edit -> Go to field "Contract Template" and create a new one
- In the "create: contract template" and an invoice line and you will get this error when adding a product:

![2017-05-07_1-11-11](https://cloud.githubusercontent.com/assets/8736623/25776582/49a7546e-32c2-11e7-86c9-fe64c4dfdf27.png)

```Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 5494, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/.repo_requirements/odoo/odoo/models.py", line 5392, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/build/OCA/contract/contract/models/account_analytic_invoice_line.py", line 85, in _onchange_product_id
    vals['price_unit'] = product.price
  File "/.repo_requirements/odoo/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/.repo_requirements/odoo/odoo/fields.py", line 981, in determine_value
    self.compute_value(recs)
  File "/.repo_requirements/odoo/odoo/fields.py", line 936, in compute_value
    self._compute_value(records)
  File "/.repo_requirements/odoo/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/odoo-10.0/addons/product/models/product.py", line 190, in _compute_product_price
    prices = pricelist.get_products_price(self, quantities, partners)
  File "/home/odoo/odoo-10.0/addons/product/models/product_pricelist.py", line 254, in get_products_price
    return dict((product_id, res_tuple[0]) for product_id, res_tuple in self._compute_price_rule(zip(products, quantities, partners), date=date, uom_id=uom_id).iteritems())
  File "/home/odoo/odoo-10.0/addons/product/models/product_pricelist.py", line 154, in _compute_price_rule
    (prod_tmpl_ids, prod_ids, categ_ids, self.id, date, date))
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: date <= boolean
LINE 1: ...1) AND (item.date_start IS NULL OR item.date_start<=false) A...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

cc @lasley @tecnativa

**Comment by lasley** [comment]
Thanks for the report @rafaelbn 

A missing piece of the replication instructions is that you have to select a pricelist as well. If you do not select a pricelist, the product adds fine.

I find it kind of weird how far up in the traceback `contract` is. I'll need to play around with this one a bit, but for the time being you can circumvent the error by not selecting a pricelist until after the invoice lines are selected (or not at all).
