### ISSUE TITLE
Error while installing new custom module

### ISSUE THREAD

**Issue by sindhu5497** [OCA/contract#688]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo13/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 421, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 202, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/odoo13/odoo/odoo/modules/registry.py", line 374, in init_models
    func()
  File "/opt/odoo13/odoo/odoo/models.py", line 2536, in mark_fields_to_compute
    recs = self.with_context(active_test=False).search([], order='id')
  File "/opt/odoo13/odoo/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo13/odoo/odoo/models.py", line 4477, in _search
    self._flush_search(args, order=order)
  File "/opt/odoo13/odoo/odoo/models.py", line 4455, in _flush_search
    self.env[model_name].flush(field_names)
  File "/opt/odoo13/odoo/odoo/models.py", line 5505, in flush
    self.recompute(fnames, records=records)
  File "/opt/odoo13/odoo/odoo/models.py", line 5943, in recompute
    fields = [self._fields[fname] for fname in fnames]
  File "/opt/odoo13/odoo/odoo/models.py", line 5943, in <listcomp>
    fields = [self._fields[fname] for fname in fnames]
KeyError: 'sale_tds'

Code:
# -*- coding: utf-8 -*-
from odoo.tools.translate import _
from odoo import models, fields, api

class TaxField(models.Model):
  _name = "tax.tds.test"
  _inherit = "sale.order"
  _description = "TDS Tax"
  transaction_ids = fields.Many2many('payment.transaction', 'sale_tds_transaction_rel', 'tax_tds_test_id', 'transaction_id',string='Transactions', copy=False, readonly=True)
  tax_tds_id = fields.Many2many(relation='tds_tds_sample',comodel_name='account.tax', string='Apply TDS', domain=['|', ('active', '=', False), ('active', '=', True)])
  #sale_tds_tax = fields.Integer(String="TDS Amount:")
  sale_tds = fields.Float(String='TDS Amount')
  #total_amount_tds_cal = fields.Monetary(string='TDS Amount', store=True, readonly=True, compute='_amount_tds', tracking=50)
  amount_total_net = fields.Monetary(string='Net Total', store=True, readonly=True, tracking=True, compute='_amount_net_total')
  _depends= {'sale.order': ['amount_total', 'sale_tds'],}
  def _amount_net_total(self):
    for rec in self:
      rec.amount_total_net = rec.amount_total + rec.sale_tds

**Comment by pedrobaeza** [comment]
This has nothing to do with this repo, but the custom module.

**Comment by sindhu5497** [comment]
want to add two fields in sale order but it shows error as Keyword...
Pls help to resolve this one

**Comment by pedrobaeza** [comment]
Not the proper place. Go to forums for asking that.
