### ISSUE TITLE
Recurring Invoices - Create Invoices

### ISSUE THREAD

**Issue by Danizan1976** [OCA/contract#76]
I'm getting error in debug mode when clicking 'Create Invoices' from Contract Recurring Invoices.
My Setup :
1) Ubuntu 16.04
2) Odoo 10 Community

![screen shot 2017-06-22 at 2 48 06 am](https://user-images.githubusercontent.com/29611383/27401255-46c5e862-56f5-11e7-9eca-b579e6b19c7a.png)

I can't seem to get the same error in runbot.
Any ideas?
--
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/contract/models/account_analytic_account.py", line 181, in recurring_create_invoice
    contract.with_context(ctx)._create_invoice()
  File "/opt/odoo/addons/contract/models/account_analytic_account.py", line 158, in _create_invoice
    invoice_vals = self._prepare_invoice()
  File "/opt/odoo/addons/contract_payment_mode/models/contract.py", line 21, in _prepare_invoice
    invoice_vals = super(AccountAnalyticAccount, self)._prepare_invoice()
  File "/opt/odoo/addons/contract/models/account_analytic_account.py", line 153, in _prepare_invoice
    return invoice._convert_to_write(invoice._cache)
  File "/opt/odoo/odoo/models.py", line 4898, in _convert_to_write
    value = field.convert_to_cache(value, self, validate=False)
  File "/opt/odoo/odoo/fields.py", line 1884, in convert_to_cache
    return process((value[0],))
IndexError: tuple index out of range
-----

**Comment by pedrobaeza** [comment]
Sorry, you should reproduce the problem on runbot or give more clues. I close meanwhile.
