### ISSUE TITLE
Keyerror when creation recurring invoice (manually or via cron)

### ISSUE THREAD

**Issue by vkhalil** [OCA/contract#952]
Hi,

Our recurring invoices suddenly top working with the following error, if someone could help. I seems to be a translation problem (we are using french locale). Seems to fail to translate month name "Mai" for "May". Can't figure out how to fix this.

## Module
contract 14.0.2.10.0

## Describe the bug
Recurring invoice stop working

## To Reproduce
contract 14.0.2.10.0

1. Create invoice from contract
2. Generate invoice from cron

**Error message**
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14/odoo-custom-addons/OCA/contract/contract/models/contract.py", line 568, in recurring_create_invoice
    invoices = self._recurring_create_invoice()
  File "/opt/odoo14/odoo-custom-addons/OCA/contract/contract/models/contract.py", line 610, in _recurring_create_invoice
    invoices_values = self._prepare_recurring_invoices_values(date_ref)
  File "/opt/odoo14/odoo-custom-addons/OCA/contract/contract/models/contract.py", line 550, in _prepare_recurring_invoices_values
    invoice_line_vals = line._prepare_invoice_line(move_form=move_form)
  File "/opt/odoo14/odoo-custom-addons/OCA/contract/contract_variable_quantity/models/contract_line.py", line 44, in _prepare_invoice_line
    vals = super()._prepare_invoice_line(move_form)
  File "/opt/odoo14/odoo-custom-addons/OCA/contract/contract/models/contract_line.py", line 576, in _prepare_invoice_line
    name = self._insert_markers(dates[0], dates[1])
  File "/opt/odoo14/odoo-custom-addons/OCA/contract/contract/models/contract_line.py", line 647, in _insert_markers
    first_date_invoiced.strftime("%B")
  File "/opt/odoo14/odoo-custom-addons/OCA/contract/contract/models/contract_line.py", line 634, in _translate_marker_month_name
    return months[month_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'mai'

**Comment by niyasraphy** [comment]
hi @vkhalil ,
seems the fix is coming in :  https://github.com/OCA/contract/pull/951
thanks

**Comment by vkhalil** [comment]
> hi @vkhalil , seems the fix is coming in : #951 thanks

Hi, cheers mate ;)

**Comment by hildickethan** [comment]
fixed with https://github.com/OCA/contract/pull/954, should be closable now

**Comment by vkhalil** [comment]
Fixed thanks
