### ISSUE TITLE
Remaining fields to compute before setting up registry

### ISSUE THREAD

**Issue by cremain** [OCA/contract#972]
Hello Team 
i request you help to resolve this issue.

## Module
Contract Management 13.0.2.10.0

## Describe the bug
Whe i want to generate contract mannually and select date, after running this error log is generated

ERROR Odoo-Test odoo.modules.registry: Remaining fields to compute before setting up registry: 
defaultdict(<class 'set'>, {account.move.line.amount_residual_currency: {<NewId 0x7f23a7f02d68>, 27353, 27354, 27352}, 
                            account.move.line.amount_residual: {<NewId 0x7f23a7f02d68>, 27353, 27354, 27352},
                            account.move.line.reconciled: {<NewId 0x7f23a7f02d68>, 27353, 27354, 27352}, 
                            account.move.amount_untaxed: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.amount_residual: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.amount_total_signed: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.amount_total: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.invoice_payment_state: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.amount_tax_signed: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.amount_tax: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.amount_untaxed_signed: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.amount_residual_signed: {<NewId 0x7f23aa8db748>, 7059}, 
                            account.move.line.tax_audit: {<NewId 0x7f23a7f02d68>, 27353, 27354, 27352}, 
                            account.move.invoice_partner_display_name: {7059}, 
                            account.move.commercial_partner_id: {7059}, 
                            account.move.line.parent_state: {27352, 27353, 27354}, 
                            account.move.line.tax_line_id: {27352, 27353, 27354}, 
                            account.move.line.account_internal_type: {27352, 27353, 27354}, 
                            account.move.line.balance: {27352, 27353, 27354}, 
                            account.move.line.ref: {27352, 27353, 27354}, 
                            account.move.line.tax_group_id: {27352, 27353, 27354}, 
                            account.move.line.account_root_id: {27352, 27353, 27354}, 
                            account.move.line.company_currency_id: {27352, 27353, 27354}, 
                            contract.line.recurring_next_date: {495}}) 
Stack (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo13/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/opt/odoo/odoo13/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo13/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1457, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo13/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo/odoo13/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo13/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo13/addons/http_routing/models/ir_http.py", line 519, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo13/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo13/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo13/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo13/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo13-custom-addons/contract/wizards/contract_manually_create_invoice.py", line 54, in create_invoice
    invoices |= contract.recurring_create_invoice()
  File "/opt/odoo/odoo13-custom-addons/contract/models/contract.py", line 534, in recurring_create_invoice
    invoice = self._recurring_create_invoice()
  File "/opt/odoo/odoo13-custom-addons/contract/models/contract.py", line 561, in _recurring_create_invoice
    invoices_values = self._prepare_recurring_invoices_values(date_ref)
  File "/opt/odoo/odoo13-custom-addons/contract/models/contract.py", line 513, in _prepare_recurring_invoices_values
    invoice_vals, move_form = contract._prepare_invoice(date_ref)
  File "/opt/odoo/odoo13-custom-addons/contract_extend/models/contract.py", line 31, in _prepare_invoice
    invoice_vals, move_form = super(ContractContract, self)._prepare_invoice(date_invoice, journal)
  File "/opt/odoo/odoo13-custom-addons/contract/models/contract.py", line 397, in _prepare_invoice
    force_company=self.company_id.id, default_type=invoice_type
  File "/opt/odoo/odoo13/odoo/tests/common.py", line 1444, in __init__
    self._process_fvg(recordp, fvg)
  File "/opt/odoo/odoo13/odoo/tests/common.py", line 1528, in _process_fvg
    self._o2m_set_edition_view(descr, f, level)
  File "/opt/odoo/odoo13/odoo/tests/common.py", line 1472, in _o2m_set_edition_view
    .load_views([(False, 'tree'), (False, 'form')])['fields_views']
  File "/opt/odoo/odoo13/odoo/models.py", line 1471, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/odoo13/odoo/models.py", line 1471, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/odoo13/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/opt/odoo/odoo13/odoo/models.py", line 1558, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 982, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 912, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 912, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 912, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  [Previous line repeated 2 more times]
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 834, in postprocess
    view_is_editable=editable,
  File "/opt/odoo/odoo13/odoo/models.py", line 5186, in with_context
    return self.with_env(self.env(context=context))
  File "/opt/odoo/odoo13/odoo/api.py", line 497, in __call__
    return Environment(cr, uid, context, su)
  File "/opt/odoo/odoo13/odoo/api.py", line 446, in __new__
    self.registry = Registry(cr.dbname)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo13/odoo/modules/loading.py", line 432, in load_modules
    registry.setup_models(cr)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 244, in setup_models
    env.all.tocompute, stack_info=True,
2023-07-03 10:01:26,175 213449 INFO Odoo-Test odoo.modules.loading: Modules loaded. 
2023-07-03 10:01:26,210 213449 WARNING Odoo-Test odoo.modules.loading: Transient module states were reset 
2023-07-03 10:01:26,210 213449 ERROR Odoo-Test odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/odoo13/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'Odoo-Test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 27352

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/fields.py", line 1037, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo13/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.move.line(27352,).parent_state', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/models.py", line 5925, in process
    recs.mapped(field.name)
  File "/opt/odoo/odoo13/odoo/models.py", line 5307, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/opt/odoo/odoo13/odoo/models.py", line 5266, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/opt/odoo/odoo13/odoo/models.py", line 5266, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/opt/odoo/odoo13/odoo/models.py", line 5731, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo13/odoo/fields.py", line 1050, in __get__
    _("(Record: %s, User: %s)") % (record, env.uid),
odoo.exceptions.MissingError: ('Recording non-existent or destroyed.\n(Record: account.move.line(27352,), Utilisateur: 1)', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo13/odoo/modules/loading.py", line 540, in load_modules
    env['base'].flush()
  File "/opt/odoo/odoo13/odoo/models.py", line 5499, in flush
    self.recompute()
  File "/opt/odoo/odoo13/odoo/models.py", line 5941, in recompute
    process(field)
  File "/opt/odoo/odoo13/odoo/models.py", line 5932, in process
    for f in recs._field_computed[field]:
KeyError: account.move.line.parent_state
2023-07-03 10:01:26,212 213449 ERROR Odoo-Test odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/odoo13/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'Odoo-Test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 27352

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/fields.py", line 1037, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo13/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.move.line(27352,).parent_state', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/models.py", line 5925, in process
    recs.mapped(field.name)
  File "/opt/odoo/odoo13/odoo/models.py", line 5307, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/opt/odoo/odoo13/odoo/models.py", line 5266, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/opt/odoo/odoo13/odoo/models.py", line 5266, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/opt/odoo/odoo13/odoo/models.py", line 5731, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo13/odoo/fields.py", line 1050, in __get__
    _("(Record: %s, User: %s)") % (record, env.uid),
odoo.exceptions.MissingError: ('Enregistrement inexistant ou détruit.\n(Enregistrement: account.move.line(27352,), Utilisateur: 1)', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo13/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo13/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo13/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo13/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo13-custom-addons/contract/wizards/contract_manually_create_invoice.py", line 54, in create_invoice
    invoices |= contract.recurring_create_invoice()
  File "/opt/odoo/odoo13-custom-addons/contract/models/contract.py", line 534, in recurring_create_invoice
    invoice = self._recurring_create_invoice()
  File "/opt/odoo/odoo13-custom-addons/contract/models/contract.py", line 561, in _recurring_create_invoice
    invoices_values = self._prepare_recurring_invoices_values(date_ref)
  File "/opt/odoo/odoo13-custom-addons/contract/models/contract.py", line 513, in _prepare_recurring_invoices_values
    invoice_vals, move_form = contract._prepare_invoice(date_ref)
  File "/opt/odoo/odoo13-custom-addons/contract_extend/models/contract.py", line 31, in _prepare_invoice
    invoice_vals, move_form = super(ContractContract, self)._prepare_invoice(date_invoice, journal)
  File "/opt/odoo/odoo13-custom-addons/contract/models/contract.py", line 397, in _prepare_invoice
    force_company=self.company_id.id, default_type=invoice_type
  File "/opt/odoo/odoo13/odoo/tests/common.py", line 1444, in __init__
    self._process_fvg(recordp, fvg)
  File "/opt/odoo/odoo13/odoo/tests/common.py", line 1528, in _process_fvg
    self._o2m_set_edition_view(descr, f, level)
  File "/opt/odoo/odoo13/odoo/tests/common.py", line 1472, in _o2m_set_edition_view
    .load_views([(False, 'tree'), (False, 'form')])['fields_views']
  File "/opt/odoo/odoo13/odoo/models.py", line 1471, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/odoo13/odoo/models.py", line 1471, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/odoo13/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/opt/odoo/odoo13/odoo/models.py", line 1558, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 982, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 912, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 912, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 912, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  [Previous line repeated 2 more times]
  File "/opt/odoo/odoo13/odoo/addons/base/models/ir_ui_view.py", line 834, in postprocess
    view_is_editable=editable,
  File "/opt/odoo/odoo13/odoo/models.py", line 5186, in with_context
    return self.with_env(self.env(context=context))
  File "/opt/odoo/odoo13/odoo/api.py", line 497, in __call__
    return Environment(cr, uid, context, su)
  File "/opt/odoo/odoo13/odoo/api.py", line 446, in __new__
    self.registry = Registry(cr.dbname)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo13/odoo/modules/loading.py", line 540, in load_modules
    env['base'].flush()
  File "/opt/odoo/odoo13/odoo/models.py", line 5499, in flush
    self.recompute()
  File "/opt/odoo/odoo13/odoo/models.py", line 5941, in recompute
    process(field)
  File "/opt/odoo/odoo13/odoo/models.py", line 5932, in process
    for f in recs._field_computed[field]:
KeyError: account.move.line.parent_state
2023-07-03 10:01:26,222 213449 INFO Odoo odoo.modules.loading: loading 1 modules... 
2023-07-03 10:01:26,240 213449 INFO Odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2023-07-03 10:01:26,263 213449 INFO Odoo odoo.modules.loading: loading 48 modules... 
2023-07-03 10:01:26,351 213449 INFO Odoo odoo.modules.loading: 48 modules loaded in 0.09s, 0 queries 
2023-07-03 10:01:26,507 213449 INFO Odoo odoo.modules.loading: Modules loaded. 
2023-07-03 10:01:26,513 213449 INFO Odoo werkzeug: 41.223.235.238 - - [03/Jul/2023 10:01:26] "POST /longpolling/poll HTTP/1.1" 200 - 56 0.051 51.321
2023-07-03 10:01:26,520 213449 INFO Odoo-Test odoo.modules.loading: loading 1 modules... 
2023-07-03 10:01:26,540 213449 INFO Odoo-Test odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2023-07-03 10:01:26,563 213449 INFO Odoo-Test odoo.modules.loading: loading 48 modules... 
2023-07-03 10:01:26,653 213449 INFO Odoo-Test odoo.modules.loading: 48 modules loaded in 0.09s, 0 queries 
2023-07-03 10:01:26,655 213449 ERROR Odoo-Test odoo.modules.registry: Remaining fields to compute before setting up registry: defaultdict(<class 'set'>, {account.move.line.amount_residual_currency: {<NewId 0x7f23a7f02d68>}, account.move.line.amount_residual: {<NewId 0x7f23a7f02d68>}, account.move.line.reconciled: {<NewId 0x7f23a7f02d68>}, account.move.amount_untaxed: {<NewId 0x7f23aa8db748>}, account.move.amount_residual: {<NewId 0x7f23aa8db748>}, account.move.amount_total_signed: {<NewId 0x7f23aa8db748>}, account.move.amount_total: {<NewId 0x7f23aa8db748>}, account.move.invoice_payment_state: {<NewId 0x7f23aa8db748>}, account.move.amount_tax_signed: {<NewId 0x7f23aa8db748>}, account.move.amount_tax: {<NewId 0x7f23aa8db748>}, account.move.amount_untaxed_signed: {<NewId 0x7f23aa8db748>}, account.move.amount_residual_signed: {<NewId 0x7f23aa8db748>}, account.move.line.tax_audit: {<NewId 0x7f23a7f02d68>}, account.move.line.parent_state: {27352, 27353, 27354}, account.move.line.tax_line_id: {27352, 27353, 27354}, account.move.line.account_internal_type: {27352, 27353, 27354}, account.move.line.ref: {27352, 27353, 27354}, account.move.line.tax_group_id: {27352, 27353, 27354}, account.move.line.account_root_id: {27352, 27353, 27354}, account.move.line.company_currency_id: {27352, 27353, 27354}, contract.line.recurring_next_date: {495}, account.move.line.balance: {27352, 27353, 27354}}) 
Stack (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo13/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/opt/odoo/odoo13/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo13/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/odoo13-venv/lib64/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1461, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo/odoo13/odoo/http.py", line 284, in __exit__
    elif self.registry:
  File "/opt/odoo/odoo13/odoo/http.py", line 368, in registry
    return odoo.registry(self.db)
  File "/opt/odoo/odoo13/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo13/odoo/modules/loading.py", line 432, in load_modules
    registry.setup_models(cr)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 244, in setup_models
    env.all.tocompute, stack_info=True,
2023-07-03 10:01:26,818 213449 INFO Odoo-Test odoo.modules.loading: Modules loaded. 
2023-07-03 10:01:26,828 213449 WARNING Odoo-Test odoo.modules.loading: Transient module states were reset 
2023-07-03 10:01:26,828 213449 ERROR Odoo-Test odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/odoo13/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'Odoo-Test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 27352

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/fields.py", line 1037, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo13/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.move.line(27352,).parent_state', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/models.py", line 5925, in process
    recs.mapped(field.name)
  File "/opt/odoo/odoo13/odoo/models.py", line 5307, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/opt/odoo/odoo13/odoo/models.py", line 5266, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/opt/odoo/odoo13/odoo/models.py", line 5266, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/opt/odoo/odoo13/odoo/models.py", line 5731, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo13/odoo/fields.py", line 1050, in __get__
    _("(Record: %s, User: %s)") % (record, env.uid),
odoo.exceptions.MissingError: ('Record does not exist or has been deleted.\n(Record: account.move.line(27352,), User: 1)', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo13/odoo/modules/loading.py", line 540, in load_modules
    env['base'].flush()
  File "/opt/odoo/odoo13/odoo/models.py", line 5499, in flush
    self.recompute()
  File "/opt/odoo/odoo13/odoo/models.py", line 5941, in recompute
    process(field)
  File "/opt/odoo/odoo13/odoo/models.py", line 5932, in process
    for f in recs._field_computed[field]:
KeyError: account.move.line.parent_state
2023-07-03 10:01:26,830 213449 INFO Odoo-Test werkzeug: 10.226.1.22 - - [03/Jul/2023 10:01:26] "POST /web/dataset/call_button HTTP/1.1" 500 - 64620 15.172 30.668
2023-07-03 10:01:26,837 213449 ERROR Odoo-Test werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo13/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/opt/odoo/odoo13/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo13/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/odoo13-venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo13/odoo/http.py", line 1461, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo/odoo13/odoo/http.py", line 284, in __exit__
    elif self.registry:
  File "/opt/odoo/odoo13/odoo/http.py", line 368, in registry
    return odoo.registry(self.db)
  File "/opt/odoo/odoo13/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/opt/odoo/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo13/odoo/modules/loading.py", line 540, in load_modules
    env['base'].flush()
  File "/opt/odoo/odoo13/odoo/models.py", line 5499, in flush
    self.recompute()
  File "/opt/odoo/odoo13/odoo/models.py", line 5941, in recompute
    process(field)
  File "/opt/odoo/odoo13/odoo/models.py", line 5932, in process
    for f in recs._field_computed[field]:
KeyError: account.move.line.parent_state - - -
2023-07-03 10:01:27,021 213449 INFO Odoo odoo.modules.loading: loading 1 modules... 
2023-07-03 10:01:27,038 213449 INFO Odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries

Thanks

**Comment by pedrobaeza** [comment]
Please reproduce the problem in runboat, as this seems something on your end. Runboat can be launched from the README.
